version: '3.8'

services:
  app:
    container_name: assessment_dev
    image: kuncikoin/assessment:dev
    build:
      context: .
      target: development
      dockerfile: ./build/docker/dockerfile
    command: npm run start:dev
    environment:
      - "NODE_ENV=${NODE_ENV}"
      - "PORT_IN=${PORT_IN}"
      - "JWT_SUPER_SECRET=${JWT_SUPER_SECRET}"
      - "JWT_EXPIRE_IN=${JWT_EXPIRE_IN}"
      - "THEAPI_ENDPOINT=${THEAPI_ENDPOINT}"
    ports:
      - "${PORT_OUT}:${PORT_IN}"
    networks:
      - swj-networks
    restart: unless-stopped
    
networks:
    medisy-networks:
        external: true
